// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package wire

import (
	"github.com/krmahadevan/di"
)

// Injectors from wire.go:

func NewServerInstance() (*di.Server, error) {
	config := di.NewConfig()
	db, err := di.ConnectDatabase(config)
	if err != nil {
		return nil, err
	}
	personRepository := di.NewPersonRepository(db)
	personService := di.NewPersonService(config, personRepository)
	server := di.NewServer(config, personService)
	return server, nil
}
